# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='empaque',
            field=models.CharField(default='Aerosol', max_length=100, verbose_name='empaque'),
        ),
    ]
