# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_presentacion_empaque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'industria',
            },
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=100, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='industria',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto'),
        ),
    ]
