# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0004_remove_industria_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='productos',
            field=models.ManyToManyField(to='Producto.Producto'),
        ),
    ]
