# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_industria_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='grado_alimenticio',
            field=models.CharField(default='No', max_length=10, verbose_name='grado_alimenticio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.CharField(default='Si', max_length=100, verbose_name='disponibilidad'),
        ),
    ]
