# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-12 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_auto_20170831_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='imagen',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='img/categorias/', width_field='width_field'),
        ),
    ]
