# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-14 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0007_industria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/categorias/'),
        ),
    ]
