# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0008_auto_20170913_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_contenido',
            field=models.CharField(default='Litros', max_length=100, verbose_name='tipo_contenido'),
        ),
    ]
