# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0009_producto_tipo_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_contenido',
        ),
    ]
