# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0011_producto_pronostico_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_contenido',
            field=models.CharField(default='Litros', max_length=200, verbose_name='tipo_contenido'),
        ),
    ]
