# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_producto_tipo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ficha_comercial_alimentaria',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_comercial_cementeras',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_comercial_gruas',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_comercial_litografias',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales/'),
        ),
    ]
