# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0013_auto_20171228_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ficha_comercial_alimentaria',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales-alimentaria/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ficha_comercial_cementeras',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales-cementeras/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ficha_comercial_gruas',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales-gruas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ficha_comercial_litografias',
            field=models.FileField(blank=True, null=True, upload_to='fichas-comerciales-litografias/'),
        ),
    ]
