# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-30 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0014_auto_20171228_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='unidades_en_stock',
            field=models.IntegerField(default=1000, verbose_name='unidades_en_stock'),
        ),
    ]
