# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0015_presentacion_unidades_en_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
