# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0017_presentacion_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
