# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-08 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0019_auto_20180207_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='image_default.png', height_field='height_field', null=True, upload_to='img/categorias/', width_field='width_field'),
        ),
    ]
