# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Producto', '0008_auto_20170913_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listado_Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_periodo', models.CharField(max_length=100, verbose_name='referencia_periodo')),
            ],
            options={
                'db_table': 'listado_productos',
            },
        ),
        migrations.CreateModel(
            name='Producto_Importacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(default='', max_length=100, null=True, verbose_name='cantidad')),
                ('tipo_contenido', models.CharField(default='', max_length=100, null=True, verbose_name='tipo_contenido')),
                ('pronostico', models.CharField(default='200', max_length=100, null=True, verbose_name='pronostico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Producto')),
            ],
            options={
                'db_table': 'producto_importacion',
            },
        ),
        migrations.AddField(
            model_name='listado_productos',
            name='productos',
            field=models.ManyToManyField(to='Demanda.Producto_Importacion'),
        ),
    ]
