# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demanda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_importacion',
            name='cantidad',
        ),
    ]
