# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demanda', '0002_remove_producto_importacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_importacion',
            name='cantidad',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='cantidad'),
        ),
    ]
