# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-25 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demanda', '0003_producto_importacion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto_importacion',
            name='cantidad',
            field=models.CharField(default='0', max_length=100, null=True, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='producto_importacion',
            name='pronostico',
            field=models.CharField(default='0', max_length=100, null=True, verbose_name='pronostico'),
        ),
    ]
