# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0012_producto_tipo_contenido'),
        ('Demanda', '0004_auto_20170925_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacion_Futura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=100, verbose_name='cantidad')),
                ('probabilidad', models.CharField(max_length=10, verbose_name='probabilidad')),
                ('mes_aplicacion', models.CharField(max_length=10, verbose_name='mes_aplicacion')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Producto.Presentacion')),
            ],
            options={
                'db_table': 'Aplicacion_Futura',
            },
        ),
        migrations.AddField(
            model_name='producto_importacion',
            name='aplicaciones_futuras_total',
            field=models.CharField(default='0', max_length=20, verbose_name='aplicaciones_futuras_total'),
        ),
        migrations.AddField(
            model_name='producto_importacion',
            name='pronostico_total',
            field=models.CharField(default='0', max_length=20, verbose_name='total_pronostico'),
        ),
    ]
