# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-27 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demanda', '0005_auto_20170926_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_importacion',
            name='aplicaciones_futuras',
            field=models.ManyToManyField(to='Demanda.Aplicacion_Futura'),
        ),
    ]
