# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-05 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demanda', '0007_auto_20171204_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto_aplicacion_futura',
            name='referencia_periodo',
            field=models.CharField(max_length=100, null=True, verbose_name='referencia_periodo'),
        ),
    ]
