# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('razon_social', models.CharField(max_length=100, verbose_name='razon social')),
                ('nit', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='nit')),
                ('sigla', models.CharField(max_length=100, verbose_name='sigla')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('tipo', models.CharField(default='', max_length=100, verbose_name='tipo')),
                ('departamento', models.CharField(max_length=100, verbose_name='departamento')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.CharField(default='', max_length=100, null=True, verbose_name='telefono')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('correo_electronico', models.EmailField(default='', max_length=254, null=True, verbose_name='correo electronico')),
                ('telefono', models.CharField(default='', max_length=100, null=True, verbose_name='telefono')),
                ('extension', models.CharField(default='', max_length=100, null=True, verbose_name='extension')),
                ('celular', models.CharField(default='', max_length=100, null=True, verbose_name='celular')),
                ('cargo', models.CharField(default='', max_length=100, null=True, verbose_name='cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
            ],
            options={
                'db_table': 'contacto',
            },
        ),
    ]
