# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-05 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(default='', max_length=100, verbose_name='cliente')),
                ('contacto', models.CharField(default='', max_length=100, verbose_name='contacto')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presentaciones', models.ManyToManyField(to='Producto.Presentacion')),
            ],
            options={
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.CharField(default='', max_length=100, verbose_name='encargado')),
                ('contacto', models.CharField(default='', max_length=100, verbose_name='contacto')),
                ('subtotal', models.CharField(default='', max_length=100, verbose_name='subtotal')),
                ('iva', models.CharField(default='', max_length=100, verbose_name='iva')),
                ('total', models.CharField(default='', max_length=100, verbose_name='total')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
                ('presentaciones', models.ManyToManyField(to='Producto.Presentacion')),
            ],
            options={
                'db_table': 'Cotizacion',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.CharField(default='', max_length=100, verbose_name='encargado')),
                ('contacto', models.CharField(default='', max_length=100, verbose_name='contacto')),
                ('consecutivo', models.CharField(default='', max_length=100, verbose_name='consecutivo')),
                ('subtotal', models.CharField(default='', max_length=100, verbose_name='subtotal')),
                ('tipo_pago', models.CharField(default='', max_length=100, verbose_name='tipo_pago')),
                ('iva', models.CharField(default='', max_length=100, verbose_name='iva')),
                ('total', models.CharField(default='', max_length=100, verbose_name='total')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
                ('presentaciones', models.ManyToManyField(to='Producto.Presentacion')),
            ],
            options={
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Remision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encargado', models.CharField(default='', max_length=100, verbose_name='encargado')),
                ('contacto', models.CharField(default='', max_length=100, verbose_name='contacto')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.Cliente')),
                ('presentaciones', models.ManyToManyField(to='Producto.Presentacion')),
            ],
            options={
                'db_table': 'Remision',
            },
        ),
    ]
