# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_auto_20170710_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condicion_pago',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='codicion_pago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='tiempo_entrega'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='validez_oferta'),
        ),
        migrations.AddField(
            model_name='factura',
            name='condicion_pago',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='codicion_pago'),
        ),
        migrations.AddField(
            model_name='factura',
            name='tiempo_entrega',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='tiempo_entrega'),
        ),
        migrations.AddField(
            model_name='factura',
            name='validez_oferta',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='validez_oferta'),
        ),
        migrations.AddField(
            model_name='remision',
            name='condicion_pago',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='codicion_pago'),
        ),
        migrations.AddField(
            model_name='remision',
            name='tiempo_entrega',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='tiempo_entrega'),
        ),
        migrations.AddField(
            model_name='remision',
            name='validez_oferta',
            field=models.CharField(default='Inmediata', max_length=100, verbose_name='validez_oferta'),
        ),
    ]
