# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-26 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_auto_20170720_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='remision',
            name='iva',
            field=models.CharField(default='', max_length=100, verbose_name='iva'),
        ),
        migrations.AddField(
            model_name='remision',
            name='subtotal',
            field=models.CharField(default='', max_length=100, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='remision',
            name='total',
            field=models.CharField(default='', max_length=100, verbose_name='total'),
        ),
    ]
